language: php

php:
    - 5.6
    - "7.0"
    - "7.1"
    - hhvm
    - nightly



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



matrix:
    allow_failures:
        - php: "7.0"
        - php: "7.1"
        - php: nightly
        - php: hhvm



before_script:
    - make install


script:
    - make check
    - make test



notifications:
    irc: "irc.freenode.org#dbwebb"
    urls:
      - https://webhooks.gitter.im/e/6e4660b0024de67de0af
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
